import ContextProvider from "@/components/context/ContextApp";

const metadata = {
  title: {
    template: '%s | Projeto de UPX',
    default: 'Projeto de UPX'
  },
  // description: 'Generated by create next app'
};

export { metadata };

function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <head>
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <script src="https://unpkg.com/jwt-decode/build/jwt-decode.js"></script>
      </head>
      <body>
        <ContextProvider>
          {children}
        </ContextProvider>
        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script noModule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
      </body>
    </html>
  )
};

export default RootLayout;