const metadata = {
  title: {
    template: '%s | Projeto de UPX',
    default: 'Projeto de UPX'
  },
  // description: 'Generated by create next app'
};

export { metadata };

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
};

export default RootLayout;